# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2083d62e46bc6713b2b1fa9ae9a0ea5b0f7923b3a77cb75a29bb2d77d75ae34e150ae2210d7f04a504b43c30b99618a1a132f51b5c21c2daa5cebe807918b340

test:
  secret_key_base: b2d3d450e93a3e22d093538c4536f5c45ba0a1fe046539e2884c264539508d12ec2e04f305a3b93858a46798c7a4a9024713068fa2c022ece040f88c4c59db75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
